[package]
name = "keyprs"
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
chrono = "0.4.38"
clap = { version = "~4.4.18", features = ["derive"] }
escpos = { version = "0.13.0", features = ["serial_port"] }
