[package]
name = "keyprs"
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
chrono = "0.4.40"
clap = { version = "~4.4.18", features = ["derive"] }
escpos = { version = "0.12.2", features = ["serial_port"] }
