[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = [ "https://github.com/rustsec/advisory-db" ]

[licenses]
version = 2
allow = [
  "MIT",
  "Apache-2.0",
  "Unicode-DFS-2016",
  "BSD-3-Clause",
  "MPL-2.0",
]

[bans]
multiple-versions = "allow"
